export const Data = [
  {
    id: 1,
    title: " Far Cry 6",
    genre: "Action-adventure",
    price: "$50.00",
    info: "New",
    img: "/images/farcry.jpg",
    category: "Trending",
    discount: 30,
  },
  {
    id: 2,
    title: " God of War Ragnarok",
    genre: "Action-adventure",
    price: "$13.99",
    info: "New",
    img: "/images/god2.jpg",
    category: "Trending",
    discount: 30,
  },
  {
    id: 3,
    title: "Tom Clancy's Rainbow Six Extraction",
    genre: "Tactical shooter",
    price: "$39.00",
    info: "Top",
    img: "/images/tomclancy.jpg",
    category: "Trending",
    discount: 30,
  },

  {
    id: 4,
    title: "Ghost wire: Tokyo",
    genre: "Action-adventure",
    price: "$60.00",
    info: "Top",
    img: "/images/ghostwire.jpg",
    category: "New Releases",
    discount: 30,
  },

  {
    id: 5,
    title: "LEGO star Wars; The Skywalker Saga",
    genre: "Action-adventure",
    price: "$40.00",
    info: "Top",
    img: "/images/lego.jpg",
    category: "New Releases",
    discount: 30,
  },
  {
    id: 6,
    title: "Mortal Kombat 11",
    genre: "Fghting game",
    price: "$25.99",
    info: "Top",
    img: "/images/mk11.425685d878cec8667fb0.jpg",
    category: "Best Rated",
    discount: 30,
  },
  {
    id: 7,
    title: "Borderlands3",
    genre: "Action role-playing, first-person shooter",
    price: "$19.99",
    info: "Top",
    img: "/images/borderlands.jpg",
    category: "Best Rated",
    discount: 30,
  },
  {
    id: 8,

    title: "EldenRing",
    genre: "Tactical shooter",
    price: "$29.99",
    info: "Top",
    img: "/images/eldenn.d3563257d0b8b51c69a4.png",
    category: "Best Rated",
    discount: 30,
  },
  {
    id: 9,
    title: "Forspoken",
    genre: "Action-adventure",
    price: "$50.00",
    info: "New",
    img: "/images/forspoken.4b543d0877fe3bee5475.jpeg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 10,
    title: "Forza Horizon 4",
    genre: "Racing game",
    price: "$39.99",
    info: "New",
    img: "/images/forza.4542c3c2c0539bcf67c0.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 11,
    title: "God of War",
    genre: "Action-adventure",
    price: "$39.99",
    info: "New",
    img: "/images/god1.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 12,
    title: "Grand Turismo 6",
    genre: "Racing game",
    price: "$39.99",
    info: "New",
    img: "/images/granT.34a83dbd0b6439ccfe4d.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 13,
    title: "Grand Turismo 7",
    genre: "Racing game",
    price: "$39.99",
    info: "New",
    img: "/images/grangran.b30d0dcfd8d75b178307.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 14,
    title: "Spider-Man",
    genre: "Action-adventure",
    price: "$39.99",
    info: "New",
    img: "/images/miles.b0a673182247cfb53be7.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 15,
    title: "Steel Rising",
    genre: "Action-adventure",
    price: "$39.99",
    info: "New",
    img: "/images/steelrising.7351de97d70e0be30b4e.jpg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 16,
    title: "The Quarry",
    genre: "Action-adventure",
    price: "$39.99",
    info: "New",
    img: "/images/thequarry.daf9ad67a563a27648bb.jpeg",
    category: "Coming Soon",
    discount: 30,
  },
  {
    id: 17,
    title: "Vampire: The Masquerade",
    genre: "Action-adventure",
    price: "$39.99",
    info: "New",
    img: "/images/vampire.59d2baef828a24bf45df.jpg",
    category: "Coming Soon",
    discount: 30,
  },
];
