export const Data = [
  {
    id: 1,
    title: " Far Cry 5",
    genre: "Action-adventure",
    price: "$50.00",
    info: "New",
    img: "/images/farcry.jpg",
    category: "trending",
  },
  {
    id: 2,
    title: " God of War Ragnarok",
    genre: "Action-adventure",
    price: "$13.99",
    info: "New",
    img: "/images/god2.jpg",
    category: "trending",
  },
  {
    id: 3,
    title: "Tom Clancy's Rainbow Six Extraction",
    genre: "Tactical shooter",
    price: "$39.00",
    info: "Top",
    img: "/images/tomclancy.jpg",
    category: "trending",
  },

  {
    id: 4,
    title: "LEGO star Wars; The Skywalker Saga",
    genre: "Action-adventure",
    price: "$40.00",
    info: "Top",
    img: "/images/lego.jpg",
    category: "newReleases",
  },

  {
    id: 5,
    title: "EldenRing",
    genre: "Tactical shooter",
    price: "$29.99",
    info: "Top",
    // img: Img5,
    category: "BestRated",
  },
  {
    id: 6,
    title: "Mortal Kombat 11",
    genre: "Fghting game",
    price: "$25.99",
    info: "Top",
    // img: Img6,
    category: "BestRated",
  },
  {
    id: 7,
    title: "Borderlands3",
    genre: "Action role-playing, first-person shooter",
    price: "$19.99",
    info: "Top",
    img: "/images/borderlands.jpg",
    category: "BestRated",
  },
  {
    id: 8,
    title: "Ghost wire: Tokyo",
    genre: "Action-adventure",
    price: "$60.00",
    info: "Top",
    img: "/images/ghostwire.jpg",
    category: "newReleases",
  },
];
